In [5]:
import pandas as pd
import torch as th

debug_fp = "/home/luke/fragnnet/data/inference/debug.pkl"
spec_fp = "/home/luke/fragnnet/data/proc/plastchem/spec_df.pkl"

df = pd.read_pickle(spec_fp)

In [6]:
df

,spec_id,mol_id,prec_type,inst_type,frag_mode,spec_type,ion_mode,dset,dset_spec_id,ace,prec_mz,peaks,group_id
0,0,0,[M+H]+,FT,HCD,MS2,P,inference,inference_0,20.0,158.843951,"[(0.0, 0.0)]",0
1,1,0,[M+H]+,FT,HCD,MS2,P,inference,inference_1,40.0,158.843951,"[(0.0, 0.0)]",0
2,2,0,[M+H]+,FT,HCD,MS2,P,inference,inference_2,60.0,158.843951,"[(0.0, 0.0)]",0
3,3,1,[M+H]+,FT,HCD,MS2,P,inference,inference_3,20.0,338.801413,"[(0.0, 0.0)]",1
4,4,1,[M+H]+,FT,HCD,MS2,P,inference,inference_4,40.0,338.801413,"[(0.0, 0.0)]",1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
29419,29419,9806,[M+H]+,FT,HCD,MS2,P,inference,inference_29419,40.0,178.998369,"[(0.0, 0.0)]",9806
29420,29420,9806,[M+H]+,FT,HCD,MS2,P,inference,inference_29420,60.0,178.998369,"[(0.0, 0.0)]",9806
29421,29421,9807,[M+H]+,FT,HCD,MS2,P,inference,inference_29421,20.0,143.016127,"[(0.0, 0.0)]",9807
29422,29422,9807,[M+H]+,FT,HCD,MS2,P,inference,inference_29422,40.0,143.016127,"[(0.0, 0.0)]",9807
29423,29423,9807,[M+H]+,FT,HCD,MS2,P,inference,inference_29423,60.0,143.016127,"[(0.0, 0.0)]",9807

In [8]:
def sample_one_row_per_mol_id(df, n=10, random_state=69):
    mol_ids = df["mol_id"].drop_duplicates()
    if len(mol_ids) < n:
        raise ValueError(f"Expected at least {n} unique mol_ids, found {len(mol_ids)}")

    selected_mol_ids = mol_ids.sample(n=n, random_state=random_state)
    return (
        df[df["mol_id"].isin(selected_mol_ids)]
        .groupby("mol_id", group_keys=False)
        .sample(n=1, random_state=random_state)
        .reset_index(drop=True)
    )

sampled_df = sample_one_row_per_mol_id(df)
sampled_df

,spec_id,mol_id,prec_type,inst_type,frag_mode,spec_type,ion_mode,dset,dset_spec_id,ace,prec_mz,peaks,group_id
0,4638,1546,[M+H]+,FT,HCD,MS2,P,inference,inference_4638,20.0,195.076419,"[(0.0, 0.0)]",1546
1,10056,3352,[M+H]+,FT,HCD,MS2,P,inference,inference_10056,20.0,185.226377,"[(0.0, 0.0)]",3352
2,17838,5946,[M+H]+,FT,HCD,MS2,P,inference,inference_17838,20.0,245.226377,"[(0.0, 0.0)]",5946
3,18833,6277,[M+H]+,FT,HCD,MS2,P,inference,inference_18833,60.0,105.054621,"[(0.0, 0.0)]",6277
4,19494,6498,[M+H]+,FT,HCD,MS2,P,inference,inference_19494,20.0,633.077818,"[(0.0, 0.0)]",6498
5,23474,7824,[M+H]+,FT,HCD,MS2,P,inference,inference_23474,60.0,253.000650,"[(0.0, 0.0)]",7824
6,24037,8012,[M+H]+,FT,HCD,MS2,P,inference,inference_24037,40.0,97.990640,"[(0.0, 0.0)]",8012
7,26857,8952,[M+H]+,FT,HCD,MS2,P,inference,inference_26857,40.0,135.076419,"[(0.0, 0.0)]",8952
8,27125,9041,[M+H]+,FT,HCD,MS2,P,inference,inference_27125,60.0,210.079455,"[(0.0, 0.0)]",9041
9,28505,9501,[M+H]+,FT,HCD,MS2,P,inference,inference_28505,60.0,219.057119,"[(0.0, 0.0)]",9501

In [9]:
debug_spec_fp = "/home/luke/fragnnet/data/proc/plastchem/debug_spec_df.pkl"
sampled_df.to_pickle(debug_spec_fp)
debug_spec_fp

'/home/luke/fragnnet/data/proc/plastchem/debug_spec_df.pkl'

In [ ]:
pred_fp = "/home/luke/fragnnet/data/inference/debug.pkl"
pred_df = pd.read_pickle(pred_fp)
pred_df

{'pred_mzs': tensor([40.0182, 42.0100, 27.0229,  ..., 17.0386, 33.0335, 19.0178]),
 'pred_logprobs': tensor([ -8.6592, -20.7233, -16.3969,  ..., -12.6927, -14.7102, -15.7282]),
 'pred_batch_idxs': tensor([0, 0, 0,  ..., 8, 8, 8]),
 'pred_formula_logprobs': tensor([-3.4028e+38, -8.6592e+00, -2.0946e+01,  ..., -1.2693e+01,
         -1.4710e+01, -1.5728e+01]),
 'pred_formula_batch_idxs': tensor([0, 0, 0,  ..., 8, 8, 8]),
 'input_spec':    spec_id  mol_id prec_type inst_type frag_mode spec_type ion_mode  \
 0     4638    1546    [M+H]+        FT       HCD       MS2        P
 1    10056    3352    [M+H]+        FT       HCD       MS2        P
 2    18833    6277    [M+H]+        FT       HCD       MS2        P
 3    19494    6498    [M+H]+        FT       HCD       MS2        P
 4    23474    7824    [M+H]+        FT       HCD       MS2        P
 5    24037    8012    [M+H]+        FT       HCD       MS2        P
 6    26857    8952    [M+H]+        FT       HCD       MS2        P
 7    27125    9041    [M+H]+        FT       HCD       MS2        P
 8    28505    9501    [M+H]+        FT       HCD       MS2        P

         dset     dset_spec_id   ace     prec_mz         peaks  group_id
 0  inference   inference_4638  20.0  195.076419  [(1.0, 1.0)]      1546
 1  inference  inference_10056  20.0  185.226377  [(1.0, 1.0)]      3352
 2  inference  inference_18833  60.0  105.054621  [(1.0, 1.0)]      6277
 3  inference  inference_19494  20.0  633.077818  [(1.0, 1.0)]      6498
 4  inference  inference_23474  60.0  253.000650  [(1.0, 1.0)]      7824
 5  inference  inference_24037  40.0   97.990640  [(1.0, 1.0)]      8012
 6  inference  inference_26857  40.0  135.076419  [(1.0, 1.0)]      8952
 7  inference  inference_27125  60.0  210.079455  [(1.0, 1.0)]      9041
 8  inference  inference_28505  60.0  219.057119  [(1.0, 1.0)]      9501  ,
 'input_mol':                                               smiles  \
 0                           CC(=O)Nc1ccc(C(=O)O)cc1N
 1                                CCCC(C)CC(C)CC(C)CC
 2                                       COC(C)C(=O)O
 3  COc1cc(S(=O)(=O)O)c(C)cc1NC(=O)C(=NNc1ccc(-c2n...
 4                 N#CC(F)(F)C(F)(F)C(F)(F)C(F)(F)C#N
 5                                        NS(=O)(=O)O
 6                                       O=NN(CCO)CCO
 7                              O=S(=O)(O)CCCN1CCOCC1
 8                             Oc1ccc(Cl)cc1Cc1ccccc1

                                                 mol  mol_id      inchikey_s  \
 0  <rdkit.Chem.rdchem.Mol object at 0x7d2ae3677ec0>    1546  MJMLUICFHWSBQZ
 1  <rdkit.Chem.rdchem.Mol object at 0x7d2ae37e4e50>    3352  PEYBKVQWVSPNDC
 2  <rdkit.Chem.rdchem.Mol object at 0x7d2ae3779ee0>    6277  ICPWFHKNYYRBSZ
 3  <rdkit.Chem.rdchem.Mol object at 0x7d2bee9a7470>    6498  LOHBKMASRGAACQ
 4  <rdkit.Chem.rdchem.Mol object at 0x7d2ae1501170>    7824  PZIVXXORSILYOQ
 5  <rdkit.Chem.rdchem.Mol object at 0x7d2ae1502390>    8012  IIACRCGMVDHOTQ
 6  <rdkit.Chem.rdchem.Mol object at 0x7d2ae15255d0>    8952  YFCDLVPYFMHRQZ
 7  <rdkit.Chem.rdchem.Mol object at 0x7d2ae1525850>    9041  DVLFYONBTKHTER
 8  <rdkit.Chem.rdchem.Mol object at 0x7d2ae15258f0>    9501  NCKMMSIFQUPKCK

                                      scaffold       formula  \
 0                                    c1ccccc1     C9H10N2O3
 1                                                    C13H28
 2                                                    C4H8O3
 3  O=C(C=NNc1ccc(-c2nc3ccccc3s2)cc1)Nc1ccccc1  C26H24N4O9S3
 4                                                    C6F8N2
 5                                                    H3NO3S
 6                                                 C4H10N2O3
 7                                    C1COCCN1     C7H15NO4S
 8                         c1ccc(Cc2ccccc2)cc1     C13H11ClO

                                                inchi       mw    exact_mw  \
 0  InChI=1S/C9H10N2O3/c1-5(12)11-8-3-2-6(9(13)14)...  194.190  194.069142
 1  InChI=1S/C13H28/c1-6-8-12(4)10-13(5)9-11(3)7-2...  184.367  184.219101
 2   InChI=1S/C4H8O3/c1-3(7-2)4(5)6/h3H,1-2H3,(H,5,6)  104.105  104.047344
 3  InChI=1S/C26H24N4O9S3/c1-13-5-10-18-23(24(13)4...  632.698  632.070541
 4  InChI=1S/C6F8N2/c7-3(8,1-15)5(11,12)6(13,14)4(...  252.064  251.993374
 5           InChI=1S/H3NO3S/c1-5(2,3)4/h(H3,1,2,3,4)   97.095   96.983364
 6  InChI=1S/C4H10N2O3/c7-3-1-6(5-9)2-4-8/h7-8H,1-4H2  134.135  134.069142
 7  InChI=1S/C7H15NO4S/c9-13(10,11)7-1-2-8-3-5-12-...  209.267  209.072179
 8  InChI=1S/C13H11ClO/c14-12-6-7-13(15)11(9-12)8-...  218.683  218.049843

    num_atoms  num_bonds  charge  single_mol  num_radicals
 0         14         14       0        True             0
 1         13         12       0        True             0
 2          7          6       0        True             0
 3         42         45       0        True             0
 4         16         15       0        True             0
 5          5          4       0        True             0
 6          9          8       0        True             0
 7         13         13       0        True             0
 8         15         16       0        True             0  ,
 'input_metadata':    spec_id  mol_id  group_id     prec_mz    ce inst  adduct
 0     4638    1546      1546  195.076419  20.0   FT  [M+H]+
 1    10056    3352      3352  185.226377  20.0   FT  [M+H]+
 2    18833    6277      6277  105.054621  60.0   FT  [M+H]+
 3    19494    6498      6498  633.077818  20.0   FT  [M+H]+
 4    23474    7824      7824  253.000650  60.0   FT  [M+H]+
 5    24037    8012      8012   97.990640  40.0   FT  [M+H]+
 6    26857    8952      8952  135.076419  40.0   FT  [M+H]+
 7    27125    9041      9041  210.079455  60.0   FT  [M+H]+
 8    28505    9501      9501  219.057119  60.0   FT  [M+H]+}